# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 238c450941705e574ec32b694c0aaaf248da42a17104155c48adb2e9555cf4074eec53d1c34e1c895b347f95fbeaf122cb6214e7a71f5b70672ca2a8305a8419

test:
  secret_key_base: 1c11f1eaaddab0e56468aaadbe042c4b162abe4b12cddce6a4d7fa125cee28f2a88920a7e6b3953bb3f71bb7967716c29da834f8f09776340081652ee839d8ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
